### ISSUE TITLE
You have requested a non-existent parameter "setono_sylius_facebook.model.pixel.class".

### ISSUE THREAD

**Issue by selvakumar143** [Setono/SyliusFacebookPlugin#18]
You have requested a non-existent parameter "setono_sylius_facebook.model.pixel.class".
![Firefox_Screenshot_2020-12-05T08-34-21 133Z](https://user-images.githubusercontent.com/31120935/101237949-c933a780-3702-11eb-9295-ed45a43c42ed.png)

**Comment by loevgaard** [comment]
Hi @selvakumar143 

Please read step 2 of the readme :) 

https://github.com/Setono/SyliusFacebookPlugin#step-2-enable-the-plugin

**Comment by selvakumar143** [comment]
Ya thanks for the support it's working :)

**Comment by loevgaard** [comment]
You're welcome :)
