### ISSUE TITLE
Tracking not happening

### ISSUE THREAD

**Issue by selvakumar143** [Setono/SyliusFacebookPlugin#19]
Hi,
Tracking not happening. I have configured pixel id but it's not triggering the events
![Firefox_Screenshot_2020-12-08T11-14-59 937Z](https://user-images.githubusercontent.com/31120935/101477244-fc7d6d00-3974-11eb-8106-69990ef4e0d0.png)

activity board 

![Firefox_Screenshot_2020-12-08T11-18-17 079Z](https://user-images.githubusercontent.com/31120935/101477408-2e8ecf00-3975-11eb-92d0-4e3154d5d928.png)

**Comment by loevgaard** [comment]
Can you install the facebook pixel helper and try to debug with that? :)

**Comment by selvakumar143** [comment]
Hi, installed but no events listed in that helper

**Comment by loevgaard** [comment]
Did you install the tag bag bundle correctly?

**Comment by selvakumar143** [comment]
I have included the pixel script manually. Thanks for the support
